### ISSUE TITLE
spack-stack 1.4.1 Unified Environment (UE) Failures on Cheyenne

### ISSUE THREAD

**Issue by zach1221** [JCSDA/spack-stack#715]
**Describe the bug**
Running UFS-WM Regression Tests utilizing the new spack-stack in PR#[1707](https://github.com/ufs-community/ufs-weather-model/pull/1707)

**To Reproduce**
1. log into Cheyenne
2. git clone -b feature/spack_stack_ue https://github.com/ulmononian/ufs-weather-model
3. cd ufs-weather-model
4. git submodule update --init --recursive
5. cd tests
6. ./rt.sh -a SCSG0002 -c -e -l rt.conf

**Expected behavior**
The intel failures below there were a lot of abrupt abortions and segmentation faults.

Intel:
regional_spp_sppt_shum_skeb_intel
regional_spp_sppt_shum_skeb_dyn32_phy32_intel
datm_cdeps_control_cfsr_intel
datm_cdeps_control_gefs_intel
datm_cdeps_iau_gefs_intel 
datm_cdeps_stochy_gefs_intel
datm_cdeps_ciceC_cfsr_intel
datm_cdeps_bulk_cfsr_intel
datm_cdeps_bulk_gefs_intel 
datm_cdeps_mx025_cfsr_intel 
datm_cdeps_3072x1536_cfsr_intel
datm_cdeps_gfs_intel
datm_cdeps_debug_cfsr_intel 
datm_cdeps_control_cfsr_faster_intel 
datm_cdeps_lnd_gswp3_intel 
atmwav_control_noaero_p8_intel
![image](https://github.com/JCSDA/spack-stack/assets/99902696/4ff0a176-0d59-4f1f-9d41-c96e66cf7bfe)
![image](https://github.com/JCSDA/spack-stack/assets/99902696/c5171f7b-46a6-4ab6-8509-6a37268ce72f)

hafs_regional_atm_ocn_wav_intel
hafs_regional_telescopic_2nests_atm_intel
hafs_regional_docn_oisst_intel
hafs_global_storm_following_1nest_atm_intel
datm_cdeps_mx025_gefs_intel
![image](https://github.com/JCSDA/spack-stack/assets/99902696/37bcac6e-d956-4e93-bcb5-d0bc360bd879)

hafs_regional_specified_moving_1nest_atm_intel
hafs_regional_storm_following_1nest_atm_intel
![image](https://github.com/JCSDA/spack-stack/assets/99902696/e1c73bec-d022-4158-ae01-036444d1fcfc)

hafs_regional_docn_intel
hafs_regional_datm_cdeps_intel 
![image](https://github.com/JCSDA/spack-stack/assets/99902696/afef1a57-c0c2-409d-99c3-a492f7fd1501)

GNU:

The gnu failures appears related to openmpi issues with the new spack environment.

cpld_control_p8_gnu openmpi
cpld_control_p8_gnu
![image](https://github.com/JCSDA/spack-stack/assets/99902696/84a09944-53e8-4385-9208-a698878c7cf8)

**System:**
Cheyenne

**Additional context**

**Comment by DeniseWorthen** [comment]
I think there is still some esmf/mesh issue related to how the stack is built on cheyenne. Both the hafs_regional_datm_cdeps_intel and the datm_cdeps_mx025_gefs_intel show the same error line arising from the dshr_mod.F90:

```
! Read in the input model mesh
       model_mesh = ESMF_MeshCreate(trim(model_meshfile), fileformat=ESMF_FILEFORMAT_ESMFMESH, rc=rc)
       if (ChkErr(rc,__LINE__,u_FILE_u)) return
```

**Comment by climbfuji** [comment]
@DeniseWorthen FWIW spack-stack and ESMF in spack-stack are configured exactly the same way on all platforms.

**Comment by DeniseWorthen** [comment]
But *something* must be different. Unfortunately, with no access to core hours on cheyenne anymore, I'm unable to do more than look at zach's output.

**Comment by zach1221** [comment]
> But _something_ must be different. Unfortunately, with no access to core hours on cheyenne anymore, I'm unable to do more than look at zach's output.

@DeniseWorthen I can help debug these issues but may require some guidance on where to look. Definitely not ideal that it seems I'm the only one who can run tests, so I can help out with testing.

**Comment by ulmononian** [comment]
@zach1221 i thought all of the HAFS RTs were fixed?

**Comment by ulmononian** [comment]
can you please try re-running all previously failing tests again? we updated the stack's esmf and mapl and it may have an impact here.

**Comment by zach1221** [comment]
> can you please try re-running all previously failing tests again? we updated the stack's esmf and mapl and it may have an impact here.

This was a test run from earlier this morning/last night. Sure, I can run again.

**Comment by zach1221** [comment]
@ulmononian apologies, I meant to follow up here yesterday. After testing, these cases listed above are still failing. I'll look further into the issues today to see if I can gain additional insight into any of these failures.

**Comment by ulmononian** [comment]
@zach1221 thanks for testing and for the update (even if it is bad news). can you share the path to your rt dir? it is bizarre to me that the hafs tests we fixed are now broken since we updated esms/mapl.

**Comment by mark-a-potts** [comment]
I ran rt.sh on derecho using @climbfuji's spack-stack install yesterday and got the majority of tests to complete. This is the list of the tests that failed due to a hang of some sort--

hafs_regional_storm_following_1nest_atm_ocn_wav_intel
hafs_regional_atm_intel
hafs_regional_1nest_atm_intel
regional_spp_sppt_shum_skeb_dyn32_phy32_intel
hafs_regional_atm_ocn_wav_intel
control_c384gdas_intel
regional_atmaq_debug_intel
regional_atmaq_faster_intel
regional_spp_sppt_shum_skeb_intel
regional_atmaq_intel
cpld_bmark_p8_intel
control_c384_intel

I suspect that this may be somehow related to using OpenMP threading for the write component, but that doesn't seem to be the only issue. There were 4 tests that do not have a threaded ATM component, but still failed to complete. They are--

hafs_regional_atm_ocn_wav_intel
regional_atmaq_debug_intel
regional_atmaq_faster_intel
regional_atmaq_intel

I have not tested all the others with 2 threads for ATM, but for at least control_c384_intel, the job completed successfully when I ran it single-threaded on the ATM component.

All the rt files are located here on derecho--/lustre/desc1/scratch/mpotts/FV3_RT/rt_75889

**Comment by climbfuji** [comment]
Oh wow. I was having trouble with my own spack-stack installation with ESMF. It seems that the way I built it (to get around build failures) screwed it up. I had set ESMF_OS and ESMF_COMM manually, whereas I think I should have set only ESMF_OS and leave ESMF_COMM as mpi (if that works at all).

**Comment by climbfuji** [comment]
Other, unrelated notes:
- the directory structure on Derecho does not follow the one we agreed on and that is laid out in the project charter; we should probably fix that before we release spack-stack installations to projects like UFS and JEDI
- I asked UCAR IT to install Intel's oneAPI 2023.1.0 in addition to or instead of the existing 2023.0.0 - the latter is the version that caused us so many headaches on Hercules, worst Intel compilers since intel@2019.0.x.

**Comment by mark-a-potts** [comment]
I experienced a number of weird issues with spack today on derecho. My first thought on the failures was that we needed to install the chained environment with pio-2.5.10, so I tried to add that next to your install. For some weird reason, the install would fail with an error like it was trying to untar the source code in /desc1 and didn't have permissions. I ended up creating a binary cache of your install and then re-installing under my user name and THEN building up the chained environment, but no dice. I got the same error with control_c384_intel.  I can try some of those tests with my previous install of spack-stack-1.4.1 to see if that is any different. I'll report back.

**Comment by mark-a-potts** [comment]
Well, control_c384_intel hangs at the same place when built using my older stack. I checked out the way that ESMF is building their nightly tests for derecho, and the only special parameter they use is "ESMF_MPIRUN=mpiexec".  However, comparing the esmf.mk files for our build and theirs, it looks like they are using the ftn/cc/CC wrappers for the build. Maybe we need to build with those?

This is where the esmf.mk is for the intel-classic build--/glade/derecho/scratch/theurich/ESMF-Nightly-Testing/intel_2023.0.0-classic_mpi_O_develop/esmf/lib/libO/Unicos.intel.64.mpi.default/esmf.mk

**Comment by climbfuji** [comment]
I was wondering, yes. Thanks for the pointers. Sigh, cray. spack is trying to move away from using the cray wrappers, and they have logic that auto-detects for certain packages whether the wrappers are supposed to be used or not. We've overwritten this logic in the past for other systems (e.g. Narwhal), so maybe we should do this here and treat derecho like a traditional cray. I will give this a try.

**Comment by ulmononian** [comment]
@climbfuji any word from ucar it about installing the newer intel compiler? given the problems caused by `ifort/2021.7.1` on c5/hercules, hopefully this can be easily resolved. however, i noticed that w/ `intel/2023.0.0` on derecho, the ifort version is `2021.8.0`, not `2021.7.0` (as on c5/hercules), but maybe this version is still problematic.

**Comment by climbfuji** [comment]
Yes, I have a ticket open with CISL and they are installing 2021.9.0 / oneAPI 2023.1.0

**Comment by akubaryk** [comment]
I have been encountering similar errors during mesh generation with our coupled model ([NOAA-SWPC/GSMWAM-IPE](https://github.com/NOAA-SWPC/GSMWAM-IPE)) on Cheyenne with a personal spack-stack (and then also hand-compiling ESMF using the spack-stack modules, similar result with a hang somewhere). For what it's worth, I compiled ESMF 8.4.2 with mpt rather than impi using appropriate system netcdf-mpi/pnetcdf/pio modulefiles, and the model is running again after compiling some needed NCEPLIBS libraries on my own as well. If providing more details here is helpful, let me know.

I've long had the feeling that support for Intel MPI on Cheyenne is poor. I couldn't figure out a simple way to replace impi with mpt within the spack-stack codebase -- is that supported functionality?

**Comment by climbfuji** [comment]
> I have been encountering similar errors during mesh generation with our coupled model ([NOAA-SWPC/GSMWAM-IPE](https://github.com/NOAA-SWPC/GSMWAM-IPE)) on Cheyenne with a personal spack-stack (and then also hand-compiling ESMF using the spack-stack modules, similar result with a hang somewhere). For what it's worth, I compiled ESMF 8.4.2 with mpt rather than impi using appropriate system netcdf-mpi/pnetcdf/pio modulefiles, and the model is running again after compiling some needed NCEPLIBS libraries on my own as well. If providing more details here is helpful, let me know.
> 
> I've long had the feeling that support for Intel MPI on Cheyenne is poor. I couldn't figure out a simple way to replace impi with mpt within the spack-stack codebase -- is that supported functionality?

Short answer: no, and given that Cheyenne will sunset end of this year, we won't be spending much effort on the system.

**Comment by climbfuji** [comment]
Is the consensus here that for the ufs-weather-model, we will keep Cheyenne on hpc-stack? If so, I'll close this issue as "not planned"/"won't fix". Thanks!

**Comment by mark-a-potts** [comment]
> Is the consensus here that for the ufs-weather-model, we will keep Cheyenne on hpc-stack? If so, I'll close this issue as "not planned"/"won't fix". Thanks!

That works for me.

**Comment by ulmononian** [comment]
@climbfuji id say close it as my understanding is cheyenne won't ever go to spack. unless @zach1221 has any contention...

**Comment by zach1221** [comment]
> @climbfuji id say close it as my understanding is cheyenne won't ever go to spack. unless @zach1221 has any contention...

Yes, I think it can be closed.
